import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/src/Components/shared/navbar-menu";
import { HeroSectionOne } from "@/src/Components/Hero/page";
import { Footer } from "@/src/Components/shared/footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-900`}
      >
        {/* Navbar উপরে fixed */}
        <NavbarDemo />

        {/* HeroBanner নিচে */}
        <div className="mt-20 px-4">
        <HeroSectionOne></HeroSectionOne>
        </div>

        {/* অন্যান্য page content */}
        <main className="mt-10 px-4">{children}</main>

        <Footer></Footer>
      </body>
    </html>
  );
}
